### ISSUE TITLE
Nodejs version u are using

### ISSUE THREAD

**Issue by haddadhady** [Silur/ZeroTwo#2]
I m just need to know which nodejs version you are using in order to run the test.js file

**Comment by Silur** [comment]
I think the latest one I tested was version 15

**Comment by haddadhady** [comment]
Thank you for your reply. I am always getting the following error if if i m using nodejs 16

E:\GIT\ZeroTwo\pkg\zerotwo.js:1
import * as wasm from "./zerotwo_bg.wasm";
^^^^^^

SyntaxError: Cannot use import statement outside a module
←[90m    at Object.compileFunction (node:vm:352:18)←[39m
←[90m    at wrapSafe (node:internal/modules/cjs/loader:1025:15)←[39m
←[90m    at Module._compile (node:internal/modules/cjs/loader:1059:27)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:975:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:816:12)←[39m
←[90m    at Module.require (node:internal/modules/cjs/loader:999:19)←[39m
←[90m    at require (node:internal/modules/cjs/helpers:93:18)←[39m
    at Object.<anonymous> (E:\GIT\ZeroTwo\test.js:5:17)
←[90m    at Module._compile (node:internal/modules/cjs/loader:1095:14)←[39m

**Comment by Silur** [comment]
That's a project organization issue, you have to create a proper npm project for your `test.js` and the `pkg` directory, and label them as modules where necessary. The `test.js` is included in the repo for quick copying into the `pkg` build directory only, not for `node test.js` directly.

**Comment by Silur** [comment]
Try building with:
```bash
wasm-pack build --target=nodejs
node test.js
```

https://asciinema.org/a/ukz54KzTyLpodNLXq4R21TZDU

**Comment by haddadhady** [comment]
Thank you a lot. it works fine. i appreciate a lot your cooperation.
